%5+1
%5+1
<?php

 // Auto generated by wpfluent Installer.

return array (
  'name' => 'FluentForm',
  'slug' => 'fluentform',
  'domain_path' => '/resources/languages',
  'text_domain' => 'fluentform',
  'hook_prefix' => 'fluentform',
  'rest_namespace' => 'fluentform',
  'rest_version' => 'v1',
  'env' => 'production',
);
