%5+1
%5+1
<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-store',
	'deps' => [
		'react',
		'react-dom',
	],
];
